services:
  app:
    build:
      context: .
      target: app
    image: nets-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PORT: "8000"
      RUN_QUEUE: "true"
      RUN_SCHEDULER: "true"
    volumes:
      - storage:/var/www/html/storage
    restart: unless-stopped

volumes:
  storage: